version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskflow-db
    environment:
      POSTGRES_DB: taskflowdb
      POSTGRES_USER: taskflow_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow_user -d taskflowdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - taskflow-network

  backend:
    build: .
    container_name: taskflow-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/taskflowdb
      QUARKUS_DATASOURCE_USERNAME: taskflow_user
      QUARKUS_DATASOURCE_PASSWORD: 12345
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update

      # JWT RSA Key Configuration
      SMALLRYE_JWT_SIGN_KEY_LOCATION: /app/keys/privateKey.pem
      SMALLRYE_JWT_VERIFY_KEY_LOCATION: /app/keys/publicKey.pem
      MP_JWT_VERIFY_ISSUER: https://taskflow-app.com
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network

volumes:
  postgres_data:

networks:
  taskflow-network:
    driver: bridge
